<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Build">
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\..\Source\KdbSharp\KdbSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
